DROP DATABASE IF EXISTS juntaauga;
CREATE DATABASE IF NOT EXISTS juntaauga;
USE juntaauga;
DROP TABLE IF EXISTS  usuarios;
CREATE TABLE IF NOT EXISTS  usuarios

(
idUsuario INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
cedula VARCHAR(10) NOT NULL,
telefono VARCHAR(10) DEFAULT NULL ,
celular VARCHAR(10) DEFAULT  NULL,
direccion VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
usuario VARCHAR(75) NOT NULL,
clave VARCHAR(75)

)ENGINE=INNODB DEFAULT CHARACTER ='utf8';

