DROP DATABASE IF EXISTS juntaauga;
CREATE DATABASE IF NOT EXISTS juntaauga;
USE juntaauga;
DROP TABLE IF EXISTS  usuarios;
CREATE TABLE IF NOT EXISTS  usuarios

(
idUsuario INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
cedula VARCHAR(10) NOT NULL,
telefono VARCHAR(10) DEFAULT NULL ,
celular VARCHAR(10) DEFAULT  NULL,
direccion VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
usuario VARCHAR(75) NOT NULL,
clave VARCHAR(75)

)ENGINE=INNODB DEFAULT CHARACTER ='utf8';

DROP TABLE IF EXISTS  ovalos;
CREATE TABLE IF NOT EXISTS  ovalos

(
idOvalo INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
toma VARCHAR(100) NOT NULL,
derivacion VARCHAR(100) NOT NULL,
canalDer VARCHAR(10) NOT NULL,
subDer VARCHAR(10) DEFAULT NULL ,
dotacion VARCHAR(10) DEFAULT  NULL,
superficie VARCHAR(100) NOT NULL,
caudal VARCHAR(100) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET ='utf8';

