/*Creación de la base de datos*/
DROP DATABASE IF EXISTS juntaauga;
CREATE DATABASE IF NOT EXISTS juntaauga;
USE juntaauga;

/*Creación de la tabla Usuarios*/
DROP TABLE IF EXISTS  usuarios;
CREATE TABLE IF NOT EXISTS  usuarios

(
idUsuario INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
cedula VARCHAR(10) NOT NULL,
telefono VARCHAR(10) DEFAULT NULL ,
celular VARCHAR(10) DEFAULT  NULL,
direccion VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
usuario VARCHAR(75) NOT NULL,
clave VARCHAR(75)

)ENGINE=INNODB DEFAULT CHARACTER ='utf8';


/*Creacion de la tabla Ovalos*/
DROP TABLE IF EXISTS  ovalos;
CREATE TABLE IF NOT EXISTS  ovalos

(
idOvalo INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
toma VARCHAR(100) NOT NULL,
derivacion VARCHAR(100) NOT NULL,
canalDer VARCHAR(10) NOT NULL,
subDer VARCHAR(10) DEFAULT NULL ,
dotacion VARCHAR(10) DEFAULT  NULL,
superficie VARCHAR(100) NOT NULL,
caudal VARCHAR(100) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET ='utf8';

/*Creación de la tabla clientes*/
DROP TABLE IF EXISTS  t_clientes;
CREATE TABLE IF NOT EXISTS  t_clientes

(
idCliente INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(75) NOT NULL,
apellido VARCHAR(75) NOT NULL,
cedula VARCHAR(10) NOT NULL,
sexo VARCHAR(10) NOT NULL ,
direccion VARCHAR(100) NOT NULL,
celular VARCHAR(10) DEFAULT  NULL,
email VARCHAR(100) NOT NULL,
)ENGINE=INNODB DEFAULT CHARSET ='utf8';


/*Creación de la tabla Lotes*/
DROP TABLE IF EXISTS  t_lotes;
CREATE TABLE IF NOT EXISTS  t_lotes

(
idLote INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
clave VARCHAR(10) NOT NULL UNIQUE,
numLote VARCHAR(10) NOT NULL,
superficie VARCHAR(10) NOT NULL,
precio VARCHAR(10) NOT NULL ,
idCliente INT(11) NOT NULL,
idOvalo  INT(11) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET ='utf8';
ALTER TABLE t_lotes DROP clave;
ALTER TABLE t_lotes ADD clave VARCHAR(10) UNIQUE NOT NULL AFTER idLote;


/*Creación tabla horas*/
DROP TABLE IF EXISTS  t_horas;
CREATE TABLE IF NOT EXISTS  t_horas
(
idHora INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
horaInicio SMALLINT NOT NULL,
horaFin SMALLINT NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET ='utf8';

/*CREACIÓN TABLA HORARIO DE RIEGO*/

DROP TABLE IF EXISTS t_horaRiego;
CREATE TABLE IF NOT EXISTS t_horaRiego

(
idHoraRiego INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
idCLiente INT(11) NOT NULL,
idOvalo INT(11) NOT NULL,
claveLote INT(11) NOT NULL,
numeroLote VARCHAR(15) NOT NULL,
horaInico1 VARCHAR(12) NOT NULL,
horaFin1 VARCHAR(12) NOT NULL,
diaRiego1 VARCHAR(15) NOT NULL,
horaInico2 VARCHAR(12) NOT NULL,
horaFin2 VARCHAR(12) NOT NULL,
diaRiego2 VARCHAR(15) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET="utf8";

/*Creación tabla parametros*/

DROP TABLE IF EXISTS  t_parametros;
CREATE TABLE IF NOT EXISTS  t_parametros

(
idParametro INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
tarifae VARCHAR(10) NOT NULL,
valorRiego VARCHAR(10) NOT NULL,
multaSesion VARCHAR(10) NOT NULL,
valorMora VARCHAR(10) DEFAULT NULL 
)ENGINE=INNODB DEFAULT CHARSET ='utf8';

/*Creación de la tabla Gastos*/
 DROP TABLE IF EXISTS t_gastos;
 CREATE TABLE IF NOT EXISTS t_gastos
 (
 idGastos INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 fecha VARCHAR(30) NOT NULL,
 responsable VARCHAR(70) NOT NULL,
 cantidad VARCHAR(7) NOT NULL,
 vUnitario VARCHAR(7) NOT NULL,
 total VARCHAR(7) NOT NULL,
 descripcion VARCHAR(255) NOT NULL
 )ENGINE=INNODB DEFAULT CHARSET ='utf8';

 /*Creación tabla sesiones*/
 DROP TABLE IF EXISTS t_sesiones;
 CREATE TABLE IF NOT EXISTS  t_sesiones
 (
 idSesion INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 estado VARCHAR(5) NOT NULL,
 fecha DATETIME NOT NULL,
 idCliente INT(11) NOT NULL
 )ENGINE=INNODB DEFAULT  CHARSET='utf8';
/*Creación tabla mingas*/
DROP TABLE IF EXISTS t_mingas;
 CREATE TABLE IF NOT EXISTS  t_mingas
 (
 idMinga INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 estado VARCHAR(5) NOT NULL,
 fecha DATETIME NOT NULL,
 idCliente INT(11) NOT NULL
 )ENGINE=INNODB DEFAULT  CHARSET='utf8';

/*Creación tabla Notificaciones*/

DROP TABLE IF EXISTS t_notificaciones;
 CREATE TABLE IF NOT EXISTS  t_notificaciones
 (
 idNotificacion INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 tipo VARCHAR(10) NOT NULL,
 descripcion VARCHAR(255) NOT NULL,
 fecha varchar(25) NOT NULL
 )ENGINE=INNODB DEFAULT  CHARSET='utf8';

/*Creación de la tabla t_cobros*/
DROP TABLE IF EXISTS t_cobros;
 CREATE TABLE IF NOT EXISTS  t_cobros
 (
 idCobro INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 cliente VARCHAR(75) NOT NULL,
 tarifa VARCHAR(6) NOT NULL,
 valorRiego varchar(6) NOT NULL,
 multaSesion varchar(6) NOT NULL,
 multaMinga varchar(6) NOT NULL,
 valorMora varchar(6) NOT NULL
 total varchar(6) NOT NULL,
 estado varchar(20) NOT NULL,
 idCliente INT(11) NOT NULL
 )ENGINE=INNODB DEFAULT  CHARSET='utf8';

